### ISSUE TITLE
angular2 Error: Cannot find module "."

### ISSUE THREAD

**Issue by wuzhouyang** [inorganik/countUp.js#141]
Just use it in angular 2.2.3 and webpack. And it throw` Error: Cannot find module "."`

**Comment by wuzhouyang** [comment]
so many errors likes 
![image](https://cloud.githubusercontent.com/assets/12148043/21667923/f62facee-d337-11e6-8240-644f722e3c13.png)

**Comment by inorganik** [comment]
you must include countUp.js as well... is it included? @vigie is this anything you an help with?

**Comment by vigie** [comment]
@wuzhouyang Can you confirm the version of countup.js you are using and also that you are separately including the countup.js file as an external global dependency, as documented in the README?

**Comment by TobiasFeld** [comment]
Same here :(

**Comment by inorganik** [comment]
@vigie ^^^

**Comment by TobiasFeld** [comment]
Hi maybe this is more information for you, it looks like this is a webpack issue.
Webpack log:

WARNING in ./~/countup.js/dist/countUp.module.js
15:24 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

**Comment by inorganik** [comment]
Is anyone able to fix? If so please submit a PR - else I might have to pull angular 2 support :(

**Comment by szykov** [comment]
I use webpack and before bootstrapping I included this:

`import 'countup.js/countUp.js';`

Then in a module I added this:

import { CountUpModule } from 'countup.js/countUp.module';
...
```
@NgModule({
    imports: [..., CountUpModule],
    ...
})
```

Error disappeard but now another one appeard:

> EXCEPTION: Error in ./AboutComponent class AboutComponent - inline template:81:83 caused by: CountUp is not defined

:\

**Comment by vigie** [comment]
> I use webpack and before bootstrapping I included this:
import 'countup.js/countUp.js';
Then in a module I added this:
import { CountUpModule } from 'countup.js/countUp.module';

Yes, this is exactly how the README instructs the usage, except you should include the transpiled file from the dist/ folder and not the typescript source. I think this should fix the tslint errors also.

> providePlugin is plugin for webpack making avaialable variables globally

@szykov Can you confirm you have this working now in a webpack environment? Could you perhaps share how you configured the above plugin to solve the problem?

**Comment by szykov** [comment]
@vigie I can't tell for sure but when I tried how you suggested I most probably had the same issue as people above. Anyway, I believe I need to try it on a clean fresh project with webpack when I will have a time. And in fact I wasn't feeling right about making countUp.js available globally, at least that I use angular with a lazy loading, so I stopped trying for now.

**Comment by hameltomor** [comment]
Guys, who knows how fix it?

**Comment by inorganik** [comment]
pinging @vigie can you please make sure this is resolved?

**Comment by vigie** [comment]
It's not clear to me if there is any issue here, as per my last comment.

[As documented](https://github.com/inorganik/countUp.js#angular-2) in the README, you must make sure the `Countup` object is available to your application as a global.

This needs to be the case irrespective of how you bundle or load modules. The Angular directive is a simple wrapper around the core technology, which happens to be a javascript global.

I have never used webpack, but according to @szykov's comment there is a plugin for webpack called [ProvidePlugin](https://webpack.js.org/plugins/provide-plugin/) that is able to provide globals. People using webpack should try using this, or similar.

I will try to find time to personally verify the webpack scenario, hopefully by this weekend.

In the meantime I would recommend closing this issue, unless @szykov or @hameltomor have experienced any errors when following the instructions? I have been using this directive for a while now and never encountered any issues.

**Comment by inorganik** [comment]
Thanks very much @vigie. Closing.

**Comment by JWesorick** [comment]
I'm still having this issue with a fresh Angular 4 app. I've included the CountUpModule in my app. 

```
...
import { ClaimModule } from './claim/claim.module';

@NgModule({
  declarations: [
    AppComponent,
  ],
  imports: [
    ...
    CountUpModule
  ],
...
})

export class AppModule {}

```

And I've added

```
import 'countup.js/dist/countUp';
import 'countup.js/dist/angular-countUp';
```

to polyfills.ts.

**Comment by tskweres** [comment]
same issue as @JWesorick

**Comment by inorganik** [comment]
@JWesorick and @tskweres - in your console, when you type `CountUp`, is it defined? [Per @vigie](https://github.com/inorganik/countUp.js/issues/141#issuecomment-283434178),  you need to make sure that CountUp is a global. 

Unfortunately I stopped working with Angular on 1.x, so I can't help much, but certainly try some debugging and report back.

**Comment by tskweres** [comment]
I just ignored the Angular2x module and use CountUp directly:

import * as CountUp from 'countup.js/dist/countUp';

then using pure CountUp works just fine

**Comment by JWesorick** [comment]
Yea I also just went the route of importing it in the component. This also means its only downloaded if its used. If CountUp needs to be a global doesn't that kinda defeat the purpose of it being in an angular module?

**Comment by dolapci** [comment]
If you working in vscode and import plugins automatically (like Ctrl+.), sometimes it will generate 
import { Some } from "." .It occurs if you import modules to current file from file which in same directory. Because of that if you find this unrelevant import, you can fix it.
